-- 初始化数据：默认账号、权限定义、角色默认权限。
-- 新环境初始化时执行一次；语句尽量使用 insert ignore / not exists，避免重复执行报错。

insert into sys_user (username, password_hash, real_name, role, status, created_at, updated_at)
select 'admin', '8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918', 'Admin', 'admin', 1, now(), now()
where not exists (select 1 from sys_user where username = 'admin');

insert ignore into sys_permission (code, name, module, status, sort_order, created_at, updated_at) values
('user:list', '人员列表', '人员管理', 1, 10, now(), now()),
('user:detail', '人员详情', '人员管理', 1, 20, now(), now()),
('user:create', '新增人员', '人员管理', 1, 30, now(), now()),
('user:edit', '编辑人员', '人员管理', 1, 40, now(), now()),
('user:status', '启停人员', '人员管理', 1, 50, now(), now()),
('user:password', '重置密码', '人员管理', 1, 60, now(), now()),
('user:permission', '分配权限', '人员管理', 1, 70, now(), now()),
('customer:list', '客户列表', '客户管理', 1, 110, now(), now()),
('customer:detail', '客户详情', '客户管理', 1, 120, now(), now()),
('customer:create', '新增客户', '客户管理', 1, 130, now(), now()),
('customer:edit', '编辑客户', '客户管理', 1, 140, now(), now()),
('customer:status', '启停客户', '客户管理', 1, 150, now(), now()),
('device:list', '设备列表', '设备管理', 1, 210, now(), now()),
('device:detail', '设备详情', '设备管理', 1, 220, now(), now()),
('device:create', '新增设备', '设备管理', 1, 230, now(), now()),
('device:edit', '编辑设备', '设备管理', 1, 240, now(), now()),
('device:status', '启停设备', '设备管理', 1, 250, now(), now()),
('work-order:list', '工单列表', '工单管理', 1, 310, now(), now()),
('work-order:detail', '工单详情', '工单管理', 1, 320, now(), now()),
('work-order:create', '新增工单', '工单管理', 1, 330, now(), now()),
('work-order:edit', '工单编辑', '工单管理', 1, 340, now(), now()),
('work-order:status', '状态变更', '工单管理', 1, 350, now(), now()),
('work-order:complete', '完成工单', '工单管理', 1, 360, now(), now()),
('work-order:process', '处理记录', '工单管理', 1, 370, now(), now()),
('attachment:list', '附件列表', '附件管理', 1, 410, now(), now()),
('attachment:detail', '附件详情', '附件管理', 1, 420, now(), now()),
('attachment:upload', '上传附件', '附件管理', 1, 430, now(), now()),
('attachment:delete', '删除附件', '附件管理', 1, 440, now(), now());

insert ignore into sys_role_permission (role, permission_code, created_at) values
('admin', 'user:list', now()),
('admin', 'user:detail', now()),
('admin', 'user:create', now()),
('admin', 'user:edit', now()),
('admin', 'user:status', now()),
('admin', 'user:password', now()),
('admin', 'user:permission', now()),
('admin', 'customer:list', now()),
('admin', 'customer:detail', now()),
('admin', 'customer:create', now()),
('admin', 'customer:edit', now()),
('admin', 'customer:status', now()),
('admin', 'device:list', now()),
('admin', 'device:detail', now()),
('admin', 'device:create', now()),
('admin', 'device:edit', now()),
('admin', 'device:status', now()),
('admin', 'work-order:list', now()),
('admin', 'work-order:detail', now()),
('admin', 'work-order:create', now()),
('admin', 'work-order:edit', now()),
('admin', 'work-order:status', now()),
('admin', 'work-order:complete', now()),
('admin', 'work-order:process', now()),
('admin', 'attachment:list', now()),
('admin', 'attachment:detail', now()),
('admin', 'attachment:upload', now()),
('admin', 'attachment:delete', now()),
('online_ops', 'user:list', now()),
('online_ops', 'user:detail', now()),
('online_ops', 'customer:list', now()),
('online_ops', 'customer:detail', now()),
('online_ops', 'customer:create', now()),
('online_ops', 'customer:edit', now()),
('online_ops', 'customer:status', now()),
('online_ops', 'device:list', now()),
('online_ops', 'device:detail', now()),
('online_ops', 'device:create', now()),
('online_ops', 'device:edit', now()),
('online_ops', 'device:status', now()),
('online_ops', 'work-order:list', now()),
('online_ops', 'work-order:detail', now()),
('online_ops', 'work-order:create', now()),
('online_ops', 'work-order:edit', now()),
('online_ops', 'work-order:status', now()),
('online_ops', 'work-order:complete', now()),
('online_ops', 'work-order:process', now()),
('online_ops', 'attachment:list', now()),
('online_ops', 'attachment:detail', now()),
('online_ops', 'attachment:upload', now()),
('online_ops', 'attachment:delete', now()),
('field_engineer', 'work-order:list', now()),
('field_engineer', 'work-order:detail', now()),
('field_engineer', 'work-order:complete', now()),
('field_engineer', 'work-order:process', now()),
('field_engineer', 'attachment:list', now()),
('field_engineer', 'attachment:detail', now()),
('field_engineer', 'attachment:upload', now());
